runtime: python39

service: default
env_variables:
  JWT_SECRET: thisisasecret
  DB_USER: postgres
  DB_PASSWORD: cloudg14
  DB_HOST: 34.68.252.15
  BUCKET_NAME: 'audio_converter_g14'
instance_class: B1
manual_scaling:
  instances: 1
entrypoint: gunicorn -b 0.0.0.0:8080 'app:return_app()'