version: "3.4"

x-var: &parameters
  EMAIL_SEND: 'False'
  FROM_EMAIL: 'conversor3000@gmail.com'
  SANDBOX: ''
  KEY: ''
  DB_HOST: 10.20.224.3
  DB_USER: postgres
  DB_PASSWORD: cloudg14
services:
  simple_worker:
    platform: linux/amd64
    build: ./simple_worker
    user: root
    volumes:
      - ../shared-files/:/simple_worker/files/
    environment:
      <<: *parameters  
