version: "3.4"

x-var: &parameters
  EMAIL_SEND: 'True'
  FROM_EMAIL: 'conversor3000@gmail.com'
  EMAIL_PASSWORD: mtvmoqhbpnvgwnkw
  REDIS_HOST: ''
  DB_HOST: ''
  DB_USER: ''
  DB_PASSWORD: ''
services:
  simple_worker:
    platform: linux/amd64
    build: ./simple_worker
    user: root
    environment:
      <<: *parameters  