version: "3.4"

x-var: &parameters
  JWT_SECRET: thisisasecret
  DB_URI: postgresql://postgres@cct-db:5432/cct
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes: 
      - ./redis_data:/data
  cct-db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cct
      POSTGRES_HOST_AUTH_METHOD: trust
  ms-template:
    volumes:
        - ./ms-template/:/mnt/
    build: ./ms-template
    working_dir: /backend/
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh cct-db:5432 && gunicorn -b 0.0.0.0:5000 'app:return_app()'"
    ports:
      - "5000:5000"
    restart: on-failure
    environment:
      <<: *parameters
    depends_on:
      - cct-db