version: "3.4"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes: 
      - ./redis_data:/data
  tasks-db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./db_tasks_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tasks
      POSTGRES_HOST_AUTH_METHOD: trust
  users-db:
    image: postgres:14.5
    ports:
      - "5433:5432"
    volumes:
      - ./db_users_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_HOST_AUTH_METHOD: trust