version: "3.4"

x-var: &parameters
  JWT_SECRET: thisisasecret
  DB_USER: postgres
  DB_PASSWORD: cloudg14
  DB_HOST: 10.20.224.3
  BUCKET_NAME: 'audio_converter_g14'
services: 
  ms-tasks:
    volumes:
        - ./ms-tasks/:/mnt/
        - ../shared-files/:/backend/files/
    build: ./ms-tasks
    working_dir: /backend/
    command: "gunicorn -b 0.0.0.0:5000 'app:return_app()'"
    ports:
      - "5000:5000"
    restart: always
    environment:
      <<: *parameters
  ms-auth:
    volumes:
        - ./ms-auth/:/mnt/
    build: ./ms-auth
    working_dir: /backend/
    command: "gunicorn -b 0.0.0.0:5000 'app:return_app()'"
    ports:
      - "5001:5000"
    restart: always
    environment:
      <<: *parameters
  nginx:
    image: nginx:latest
    ports:
      - 4000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    restart: always
    depends_on:
        - ms-tasks
        - ms-auth
