runtime: python39

service: worker
env_variables:
  DB_HOST: 34.68.252.15
  DB_USER: postgres
  DB_PASSWORD: cloudg14
  BUCKET_NAME: 'audio_converter_g14'
  EMAIL_SEND: 'False'
instance_class: B1
manual_scaling:
  instances: 1
entrypoint: python3 worker.py